"""
resume_template.py

A code-driven resume generator that replicates the exact visual layout of
Abhishek Sharma's resume: fonts, sizes, margins, indentation, line spacing,
section-header rules, and bullet styles.

Feed it new CONTENT (a plain Python dict / JSON) and it renders a PDF with
the identical skeleton — only the text changes. Built for use in an
automated pipeline (e.g. a Gemini-tailored resume step) where content is
generated by code rather than typed by hand.

Usage:
    python3 resume_template.py content.json output.pdf
    # or import and call render_resume(content_dict, "out.pdf")

Inline emphasis: wrap any phrase in **double asterisks** inside summary
text or bullet text to bold it (mirrors the original resume's habit of
bolding key skill terms inside sentences).
"""

import json
import re
import sys
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ---------------------------------------------------------------------------
# Fonts
# ---------------------------------------------------------------------------
# "Lato" is used for the name, contact row, job/project titles, and dates.
# It is embedded from the open-source Lato family (identical family the
# original was built with).
#
# "Helvetica" (ReportLab's built-in, metrically equivalent to Arial) is used
# for section headers, body/bullet text, and education lines — standing in
# for the "ArialMTPro" font baked into the original PDF (a licensed Canva
# variant of Arial that can't be redistributed, but Helvetica is
# metric-compatible enough that line lengths and wrapping match closely).

LATO_REGULAR_PATH = "/usr/share/fonts/truetype/lato/Lato-Regular.ttf"
LATO_BOLD_PATH = "/usr/share/fonts/truetype/lato/Lato-Bold.ttf"

pdfmetrics.registerFont(TTFont("Lato", LATO_REGULAR_PATH))
pdfmetrics.registerFont(TTFont("Lato-Bold", LATO_BOLD_PATH))

F_NAME = "Lato"
F_TITLE = "Lato-Bold"      # job / project title, dates
F_BODY = "Helvetica"        # section headers (bold variant below), body/bullets
F_BODY_BOLD = "Helvetica-Bold"

# ---------------------------------------------------------------------------
# Page geometry (measured from the original PDF)
# ---------------------------------------------------------------------------
PAGE_W, PAGE_H = A4
ML, MR = 15.0, 15.0                 # left / right margin
CW = PAGE_W - ML - MR               # content width
IND_L2 = ML + 12                    # job/project title, skill category, edu institute
IND_L3_MARK = ML + 23               # bullet marker x
IND_L3_TXT = ML + 31                # bullet text x (after marker)
BULLET_TEXT_W = PAGE_W - MR - IND_L3_TXT

NAME_SIZE = 14.2
CONTACT_SIZE = 8
HEADER_SIZE = 10
BODY_SIZE = 8
TITLE_SIZE = 9
DATE_SIZE = 7

LEADING = 14.0                      # body/bullet line pitch (measured exactly)
GAP_BEFORE_HEADER = 12.0            # previous content bottom -> next header top
GAP_HEADER_TO_CONTENT = 8.0         # header -> first content line
GAP_TITLE_TO_BULLETS = 11.0         # job/project title -> first bullet
GAP_ENTRY_TO_ENTRY = 4.0            # end of one job/project block -> next title

COLOR_TEXT = (0, 0, 0)
COLOR_RULE = (0, 0, 0)
COLOR_MARKER_OUTER = (0.80, 0.796, 0.788)
COLOR_MARKER_INNER = (0.529, 0.631, 0.690)
COLOR_ICON = (0.44, 0.435, 0.435)


# ---------------------------------------------------------------------------
# Inline **bold** markup parsing + mixed-run word wrap
# ---------------------------------------------------------------------------
def parse_markup(text):
    """Kept for callers that want the raw (text, is_bold) run list."""
    parts = re.split(r"(\*\*.*?\*\*)", text)
    runs = []
    for p in parts:
        if not p:
            continue
        if p.startswith("**") and p.endswith("**"):
            runs.append((p[2:-2], True))
        else:
            runs.append((p, False))
    return runs


def _tokenize_markup(text):
    """Turns '...**bold**, more...' into word tokens with correct bold flags,
    without inserting spaces that weren't in the source (e.g. a comma glued
    right after a closing **)."""
    full, mask = [], []
    for chunk, bold in parse_markup(text):
        full.append(chunk)
        mask.extend([bold] * len(chunk))
    full = "".join(full)
    words = []
    for m in re.finditer(r"\S+", full):
        w = m.group()
        sub = mask[m.start(): m.start() + len(w)]
        bold = sum(sub) * 2 > len(sub)
        words.append((w, bold))
    return words


def wrap_runs(c, runs_or_text, size, max_width, font_reg=F_BODY, font_bold=F_BODY_BOLD):
    """Greedy word-wrap across mixed bold/regular text. Accepts either a raw
    markup string ('**bold** plain') or a pre-parsed run list. Returns list
    of lines; each line is a list of (word, is_bold, word_width)."""
    if isinstance(runs_or_text, str):
        words = _tokenize_markup(runs_or_text)
    else:
        words = []
        for text, bold in runs_or_text:
            for w in text.split(" "):
                if w:
                    words.append((w, bold))

    space_w = c.stringWidth(" ", font_reg, size)
    lines, current, current_w = [], [], 0.0
    for w, bold in words:
        font = font_bold if bold else font_reg
        ww = c.stringWidth(w, font, size)
        extra = space_w if current else 0.0
        if current and current_w + extra + ww > max_width:
            lines.append(current)
            current, current_w = [(w, bold, ww)], ww
        else:
            current.append((w, bold, ww))
            current_w += extra + ww
    if current:
        lines.append(current)
    return lines


def draw_mixed_line(c, x, y, line, size, font_reg=F_BODY, font_bold=F_BODY_BOLD, color=COLOR_TEXT):
    c.setFillColorRGB(*color)
    space_w = c.stringWidth(" ", font_reg, size)
    cx = x
    for i, (w, bold, ww) in enumerate(line):
        c.setFont(font_bold if bold else font_reg, size)
        c.drawString(cx, y, w)
        cx += ww
        if i < len(line) - 1:
            cx += space_w


def draw_wrapped_text(c, x, y_top, text, size, max_width, leading=LEADING,
                       font_reg=F_BODY, font_bold=F_BODY_BOLD, color=COLOR_TEXT):
    """Draws markup-aware wrapped text starting with baseline at y_top.
    Returns the y of the last baseline drawn (i.e. y_top - (n-1)*leading)."""
    lines = wrap_runs(c, text, size, max_width, font_reg, font_bold)
    y = y_top
    for line in lines:
        draw_mixed_line(c, x, y, line, size, font_reg, font_bold, color)
        y -= leading
    return y + leading  # baseline of the last line actually drawn


# ---------------------------------------------------------------------------
# Small vector icons for the contact row (simplified stand-ins for the
# original's Canva icon glyphs — same idea, drawn from primitives)
# ---------------------------------------------------------------------------
def icon_envelope(c, x, y, s=8):
    c.setStrokeColorRGB(*COLOR_ICON)
    c.setLineWidth(0.8)
    c.rect(x, y, s, s * 0.72, stroke=1, fill=0)
    c.line(x, y + s * 0.72, x + s / 2, y + s * 0.30)
    c.line(x + s, y + s * 0.72, x + s / 2, y + s * 0.30)


def icon_linkedin(c, x, y, s=8):
    c.setFillColorRGB(*COLOR_ICON)
    c.roundRect(x, y, s, s, 1.2, stroke=0, fill=1)
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica-Bold", s * 0.62)
    c.drawCentredString(x + s / 2, y + s * 0.22, "in")


def icon_phone(c, x, y, s=8):
    c.setStrokeColorRGB(*COLOR_ICON)
    c.setLineWidth(1.1)
    c.setFillColorRGB(*COLOR_ICON)
    c.circle(x + s * 0.18, y + s * 0.85, s * 0.14, stroke=0, fill=1)
    c.circle(x + s * 0.85, y + s * 0.18, s * 0.14, stroke=0, fill=1)
    p = c.beginPath()
    p.moveTo(x + s * 0.18, y + s * 0.85)
    p.curveTo(x + s * 0.3, y + s * 0.5, x + s * 0.5, y + s * 0.3, x + s * 0.85, y + s * 0.18)
    c.drawPath(p, stroke=1, fill=0)


def icon_pin(c, x, y, s=8):
    c.setFillColorRGB(*COLOR_ICON)
    c.circle(x + s / 2, y + s * 0.72, s * 0.30, stroke=0, fill=1)
    p = c.beginPath()
    p.moveTo(x + s * 0.24, y + s * 0.62)
    p.lineTo(x + s * 0.76, y + s * 0.62)
    p.lineTo(x + s / 2, y)
    p.close()
    c.drawPath(p, stroke=0, fill=1)
    c.setFillColorRGB(1, 1, 1)
    c.circle(x + s / 2, y + s * 0.72, s * 0.13, stroke=0, fill=1)


# ---------------------------------------------------------------------------
# Layout building blocks
# ---------------------------------------------------------------------------
def draw_letter_spaced_centered(c, cx, y, text, font, size, char_space):
    widths = [c.stringWidth(ch, font, size) for ch in text]
    total = sum(widths) + char_space * (len(text) - 1)
    x = cx - total / 2
    c.setFont(font, size)
    for ch, w in zip(text, widths):
        c.drawString(x, y, ch)
        x += w + char_space


def draw_name_and_contact(c, data):
    y = PAGE_H - 24
    c.setFillColorRGB(*COLOR_TEXT)
    c.setFont(F_NAME, NAME_SIZE)
    draw_letter_spaced_centered(c, PAGE_W / 2, y, data["name"].upper(), F_NAME, NAME_SIZE, 1.6)

    y -= 26
    items = []
    contact = data["contact"]
    if contact.get("email"):
        items.append(("email", contact["email"]))
    if contact.get("linkedin_label"):
        items.append(("linkedin", contact["linkedin_label"]))
    if contact.get("phone"):
        items.append(("phone", contact["phone"]))
    if contact.get("location"):
        items.append(("pin", contact["location"]))

    c.setFont(F_NAME, CONTACT_SIZE)
    icon_s = 8
    gap_icon_text = 4
    gap_between = 22
    widths = []
    for kind, text in items:
        underline = kind == "linkedin"
        w = icon_s + gap_icon_text + c.stringWidth(text, F_NAME, CONTACT_SIZE)
        widths.append(w)
    total = sum(widths) + gap_between * (len(items) - 1)
    x = (PAGE_W - total) / 2

    icon_fns = {"email": icon_envelope, "linkedin": icon_linkedin,
                "phone": icon_phone, "pin": icon_pin}
    for (kind, text), w in zip(items, widths):
        icon_fns[kind](c, x, y - icon_s * 0.72, icon_s)
        tx = x + icon_s + gap_icon_text
        c.setFillColorRGB(*COLOR_TEXT)
        c.setFont(F_NAME, CONTACT_SIZE)
        c.drawString(tx, y - 6, text)
        if kind == "linkedin":
            tw = c.stringWidth(text, F_NAME, CONTACT_SIZE)
            c.setLineWidth(0.6)
            c.setStrokeColorRGB(*COLOR_TEXT)
            c.line(tx, y - 7.5, tx + tw, y - 7.5)
        x += w + gap_between

    return y - 20  # bottom of contact row


def draw_section_header(c, y_top, title):
    c.setFillColorRGB(*COLOR_TEXT)
    c.setFont(F_BODY_BOLD, HEADER_SIZE)
    c.drawString(ML, y_top, title)
    rule_y = y_top - 3.5
    c.setStrokeColorRGB(*COLOR_RULE)
    c.setLineWidth(0.9)
    c.line(ML, rule_y, PAGE_W - MR, rule_y)
    return rule_y  # bottom edge of the header block


def draw_summary(c, y_top, text):
    return draw_wrapped_text(c, IND_L2, y_top, text, BODY_SIZE,
                              PAGE_W - MR - IND_L2, LEADING)


def draw_skills(c, y_top, skills):
    y = y_top
    for item in skills:
        runs = [(item["label"] + ": ", True), (item["value"], False)]
        lines = wrap_runs(c, runs, BODY_SIZE, PAGE_W - MR - IND_L2)
        for line in lines:
            draw_mixed_line(c, IND_L2, y, line, BODY_SIZE)
            y -= LEADING
    return y + LEADING


def draw_entry_marker(c, x, y_title_top):
    cy = y_title_top - 3.5
    c.setFillColorRGB(*COLOR_MARKER_OUTER)
    c.circle(x + 3.2, cy, 3.2, stroke=0, fill=1)
    c.setFillColorRGB(*COLOR_MARKER_INNER)
    c.circle(x + 3.2, cy, 1.7, stroke=0, fill=1)


def draw_bullet(c, x, y_baseline, hollow=False):
    r = 1.1
    cy = y_baseline + 2.6
    if hollow:
        c.setStrokeColorRGB(*COLOR_TEXT)
        c.setLineWidth(0.65)
        c.circle(x + r, cy, r, stroke=1, fill=0)
    else:
        c.setFillColorRGB(*COLOR_TEXT)
        c.rect(x, cy - r, r * 1.9, r * 1.9, stroke=0, fill=1)


def draw_entry_block(c, y_top, title, dates, bullets, tech_stack_label, tech_stack_value, hollow_bullets):
    """One job / project entry. Returns y of the bottom of the block."""
    draw_entry_marker(c, ML, y_top)
    c.setFillColorRGB(*COLOR_TEXT)
    c.setFont(F_TITLE, TITLE_SIZE)
    c.drawString(IND_L2, y_top - TITLE_SIZE * 0.78, title)
    c.setFont(F_TITLE, DATE_SIZE)
    c.drawRightString(PAGE_W - MR, y_top - TITLE_SIZE * 0.68, dates)

    y = y_top - TITLE_SIZE * 0.78 - GAP_TITLE_TO_BULLETS
    for b in bullets:
        lines = wrap_runs(c, b, BODY_SIZE, BULLET_TEXT_W)
        for i, line in enumerate(lines):
            if i == 0:
                draw_bullet(c, IND_L3_MARK, y, hollow=hollow_bullets)
            draw_mixed_line(c, IND_L3_TXT, y, line, BODY_SIZE)
            y -= LEADING

    if tech_stack_value:
        full = f"**{tech_stack_label}:** {tech_stack_value}"
        lines = wrap_runs(c, full, BODY_SIZE, BULLET_TEXT_W)
        for i, line in enumerate(lines):
            if i == 0:
                draw_bullet(c, IND_L3_MARK, y, hollow=hollow_bullets)
            draw_mixed_line(c, IND_L3_TXT, y, line, BODY_SIZE)
            y -= LEADING

    return y + LEADING


def draw_education(c, y_top, edu_list):
    y = y_top
    for edu in edu_list:
        c.setFillColorRGB(*COLOR_TEXT)
        c.setFont(F_BODY_BOLD, BODY_SIZE)
        c.drawString(IND_L2, y, edu["institute"])
        c.setFont(F_TITLE, DATE_SIZE)
        c.drawRightString(PAGE_W - MR, y + 1, edu.get("dates", ""))
        y -= LEADING
        c.setFont(F_BODY, BODY_SIZE)
        c.drawString(IND_L2, y, edu["degree"])
        if edu.get("extra"):
            c.setFont(F_TITLE, DATE_SIZE)
            c.drawRightString(PAGE_W - MR, y + 1, edu["extra"])
        y -= (LEADING + 2)
    return y + LEADING


# ---------------------------------------------------------------------------
# Main render
# ---------------------------------------------------------------------------
def render_resume(data, output_path):
    c = canvas.Canvas(output_path, pagesize=A4)

    y = draw_name_and_contact(c, data)

    y -= GAP_BEFORE_HEADER
    y = draw_section_header(c, y, "Summary")
    y -= GAP_HEADER_TO_CONTENT
    y = draw_summary(c, y, data["summary"])

    y -= GAP_BEFORE_HEADER
    y = draw_section_header(c, y, "Technical Skills")
    y -= GAP_HEADER_TO_CONTENT
    y = draw_skills(c, y, data["skills"])

    y -= GAP_BEFORE_HEADER
    y = draw_section_header(c, y, "Experience")
    y -= GAP_HEADER_TO_CONTENT
    for i, job in enumerate(data["experience"]):
        y = draw_entry_block(c, y, job["title"], job["dates"], job["bullets"],
                              "Tech Stack Used", job.get("tech_stack", ""),
                              hollow_bullets=False)
        if i < len(data["experience"]) - 1:
            y -= GAP_ENTRY_TO_ENTRY

    y -= GAP_BEFORE_HEADER
    y = draw_section_header(c, y, "Projects")
    y -= GAP_HEADER_TO_CONTENT
    for i, proj in enumerate(data["projects"]):
        y = draw_entry_block(c, y, proj["title"], proj["dates"], proj["bullets"],
                              "Tech Stack", proj.get("tech_stack", ""),
                              hollow_bullets=True)
        if i < len(data["projects"]) - 1:
            y -= GAP_ENTRY_TO_ENTRY

    y -= GAP_BEFORE_HEADER
    y = draw_section_header(c, y, "Education")
    y -= GAP_HEADER_TO_CONTENT
    draw_education(c, y, data["education"])

    c.showPage()
    c.save()


if __name__ == "__main__":
    content_path = sys.argv[1] if len(sys.argv) > 1 else "content.json"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "resume_out.pdf"
    with open(content_path) as f:
        data = json.load(f)
    render_resume(data, out_path)
    print(f"Wrote {out_path}")
